// src/react/MyComponent.jsx
import React from 'react'

const containerStyle = {
  width: '100%',
  height: '100%',
  overflow: 'hidden',
  position: 'relative',
  display: 'flex',
  flexDirection: 'column'
}

const contentStyle = {
  flex: 1,
  width: '100%',
  height: '100%',
  border: 'none'
}

const ViewDist = ({ 
  useIframe = true,
  url = 'https://lichuya.github.io/vue3-mindmap/',
  content = ''
}) => {
  return (
    <div style={containerStyle} className="advance-mind-map-container">
      {useIframe ? (
        <iframe
          src={url}
          frameBorder="0" 
          style={contentStyle}
        />
      ) : (
        <div 
          style={contentStyle}
          className="advance-mind-map-content"
          dangerouslySetInnerHTML={{ __html: content }}
        />
      )}
    </div>
  )
}

export default ViewDist

// src/vue/MyComponent.vue
<template>
  <div class="advance-mind-map-container">
    <iframe 
      v-if="useIframe"
      :src="url"
      frameborder="0"
      style="width: 100%; height: 100%; border: none; display: block;"
    ></iframe>
    <div v-else class="advance-mind-map-content" v-html="content"></div>
  </div>
</template>

<script>
export default {
  name: 'AdvanceMindMap',
  props: {
    // 是否使用iframe展示
    useIframe: {
      type: Boolean,
      default: true
    },
    // 直接传入的HTML内容
    url: {
      type: String,
      default: 'https://lichuya.github.io/vue3-mindmap/'
    },
    content: {
      type: String,
      default: ''
    }
  }
}
</script>

<style>
.advance-mind-map-container {
  width: 100%;
  height: 100%;
  overflow: hidden;
  position: relative;
  display: flex;
  flex-direction: column;
}

.advance-mind-map-container iframe,
.advance-mind-map-container .advance-mind-map-content {
  flex: 1;
  width: 100%;
  height: 100%;
  border: none;
}
</style>
